### ISSUE TITLE
Option to choose the delimiter '/'

### ISSUE THREAD

**Issue by Zacharias030** [florinionce/copy-current-file-path#39]
Feature Request:

When using python, I wish that I could copy the path of the current file relative to the workspace directory, but with dots instead of slashes, so that one can quickly find a function (any `name`) in the codebase and then import it somewhere else as

```python
from workspace.some.very.deep.package.tree import found_function
```

**Comment by florinionce** [comment]
Thank you for your suggestion. I apologize that it took so long. I published an update today, making the separator configurable.
