### ISSUE TITLE
Please, add a way to disable notification

### ISSUE THREAD

**Issue by dorian-marchal** [florinionce/copy-current-file-path#7]
Closing them is tiring.

**Comment by alfondotnet** [comment]
Just came here to ask the same, it would be very appreciated!

@florinionce  @dorian-marchal I created this PR just in case https://github.com/florinionce/copy-current-file-path/pull/8

**Comment by florinionce** [comment]
@dorian-marchal Thank you very much for the suggestion
@alfonsoperez Thank you for your contribution. However, I wanted to have the ability to chose whether we want the alerts or not, so I added an option in the settings for this. I also updated the readme. I'll make an update today in the marketplace.

**Comment by florinionce** [comment]
I'm closing this since a new version containing this feature was released
